# Site settings ...
uri: domain.com
url: https://domain.com
name: Your name
title: Mangan
email: example@domain.com
author: username
baseurl: ""
keywords: "Your, Keyword, Here"
description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione nihil, velit odio quia autem quos. Natus itaque sint, nisi fuga dolorum. Iste ea cumque, aliquam dignissimos vitae labore atque minima?"
social_username: username

# Build settings ...
sass:
  style: compressed
markdown: kramdown
encoding: "utf-8"
paginate: 5
permalink: /post/:title
paginate_path: "/page/:num/"

# Plugins ...
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
