# Site settings ...
uri: mangan.dikiaap.id
url: https://mangan.dikiaap.id
name: Your name
title: Mangan Jekyll Theme
email: example@domain.com
author: username
keywords: "Mangan, Jekyll, Theme"
description: "Geek theme for Jekyll."
social_username: username

# Build settings ...
sass:
  style: compressed
markdown: kramdown
paginate: 5
permalink: /post/:title
paginate_path: "/page/:num/"
exclude:
  - README.md

# Plugins ...
plugins:
  - jekyll-paginate
  - jemoji